# Pages CMS Configuration for Astro Starlight
# Place this file in the root of your repository

# Media configuration
media: src/assets

# Content types
content:
  - name: docs
    label: Documentation
    type: collection
    path: src/content/docs
    fields:
      - name: title
        label: Title
        type: string
        required: true
      
      - name: description
        label: Description
        type: text
      
      - name: body
        label: Content
        type: rich-text

    # Collection view settings
    view:
      fields: [title, description]
      primary: title
    
    # Filename pattern
    filename: '{title}.md'